// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package openapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ErrorEnvelopeCode.
const (
	ErrorEnvelopeCodeAgentReadOnly  ErrorEnvelopeCode = "agent_read_only"
	ErrorEnvelopeCodeAuthRequired   ErrorEnvelopeCode = "auth_required"
	ErrorEnvelopeCodeBadRequest     ErrorEnvelopeCode = "bad_request"
	ErrorEnvelopeCodeFreeTierLocked ErrorEnvelopeCode = "free_tier_locked"
	ErrorEnvelopeCodeInternalError  ErrorEnvelopeCode = "internal_error"
	ErrorEnvelopeCodeNotFound       ErrorEnvelopeCode = "not_found"
	ErrorEnvelopeCodeOwnerTeamLost  ErrorEnvelopeCode = "owner_team_lost"
	ErrorEnvelopeCodeRateLimited    ErrorEnvelopeCode = "rate_limited"
	ErrorEnvelopeCodeTokenRevoked   ErrorEnvelopeCode = "token_revoked"
)

// Defines values for MeCapabilities.
const (
	AttachmentDownload  MeCapabilities = "attachment_download"
	PinFieldSelection   MeCapabilities = "pin_field_selection"
	ScopedPinLookup     MeCapabilities = "scoped_pin_lookup"
	ScopedSessionLookup MeCapabilities = "scoped_session_lookup"
	Search              MeCapabilities = "search"
)

// Defines values for SessionDetailStatus.
const (
	SessionDetailStatusDismissed SessionDetailStatus = "dismissed"
	SessionDetailStatusOpen      SessionDetailStatus = "open"
	SessionDetailStatusResolved  SessionDetailStatus = "resolved"
)

// Defines values for SessionSummaryStatus.
const (
	SessionSummaryStatusDismissed SessionSummaryStatus = "dismissed"
	SessionSummaryStatusOpen      SessionSummaryStatus = "open"
	SessionSummaryStatusResolved  SessionSummaryStatus = "resolved"
)

// Defines values for SearchParamsScope.
const (
	Pins     SearchParamsScope = "pins"
	Sessions SearchParamsScope = "sessions"
)

// Defines values for ListSessionsParamsStatus.
const (
	Dismissed ListSessionsParamsStatus = "dismissed"
	Open      ListSessionsParamsStatus = "open"
	Resolved  ListSessionsParamsStatus = "resolved"
)

// Defines values for GetPinByNumberParamsFields.
const (
	ConsoleLogs    GetPinByNumberParamsFields = "console_logs"
	NetworkLogs    GetPinByNumberParamsFields = "network_logs"
	Screenshot     GetPinByNumberParamsFields = "screenshot"
	SessionReplay  GetPinByNumberParamsFields = "session_replay"
	UserEvents     GetPinByNumberParamsFields = "user_events"
	VideoRecording GetPinByNumberParamsFields = "video_recording"
	VoiceNote      GetPinByNumberParamsFields = "voice_note"
)

// Asset defines model for Asset.
type Asset struct {
	ContentType string    `json:"content_type"`
	ExpiresAt   time.Time `json:"expires_at"`
	SizeBytes   *int      `json:"size_bytes"`
	Url         string    `json:"url"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	ContentType string `json:"content_type"`
	Filename    string `json:"filename"`
	Id          int    `json:"id"`
	SizeBytes   int    `json:"size_bytes"`
}

// ConsoleLogItem defines model for ConsoleLogItem.
type ConsoleLogItem struct {
	Datetime             *string                `json:"datetime,omitempty"`
	EpochTime            *float32               `json:"epochTime,omitempty"`
	Extra                *interface{}           `json:"extra,omitempty"`
	FullUrl              *string                `json:"full_url,omitempty"`
	ShortUrl             *string                `json:"short_url,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	Value                *interface{}           `json:"value,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Code      ErrorEnvelopeCode `json:"code"`
	Detail    string            `json:"detail"`
	RequestId string            `json:"request_id"`
}

// ErrorEnvelopeCode defines model for ErrorEnvelope.Code.
type ErrorEnvelopeCode string

// ListSessionsResponse defines model for ListSessionsResponse.
type ListSessionsResponse struct {
	Count             int              `json:"count"`
	FreeTierTruncated bool             `json:"free_tier_truncated"`
	NextCursor        *string          `json:"next_cursor"`
	Results           []SessionSummary `json:"results"`
}

// Me defines model for Me.
type Me struct {
	AgentName      string              `json:"agent_name"`
	ApiVersion     string              `json:"api_version"`
	Capabilities   []MeCapabilities    `json:"capabilities"`
	CreatedByEmail openapi_types.Email `json:"created_by_email"`
	LastUsedAt     time.Time           `json:"last_used_at"`
	Team           string              `json:"team"`
	TeamSlug       string              `json:"team_slug"`
	TokenPrefix    string              `json:"token_prefix"`
}

// MeCapabilities defines model for Me.Capabilities.
type MeCapabilities string

// NetworkLogItem defines model for NetworkLogItem.
type NetworkLogItem struct {
	Body                 *interface{}           `json:"body,omitempty"`
	EpochTime            *float32               `json:"epochTime,omitempty"`
	FullUrl              *string                `json:"full_url,omitempty"`
	Headers              *interface{}           `json:"headers,omitempty"`
	Method               *string                `json:"method,omitempty"`
	ShortUrl             *string                `json:"short_url,omitempty"`
	Status               *int                   `json:"status,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PinFull defines model for PinFull.
type PinFull struct {
	Attachments    []Attachment           `json:"attachments"`
	Console        *[]ConsoleLogItem      `json:"console,omitempty"`
	ElementInfo    map[string]interface{} `json:"element_info"`
	Events         *[]UserEventItem       `json:"events,omitempty"`
	Feedback       string                 `json:"feedback"`
	Metadata       map[string]interface{} `json:"metadata"`
	Network        *[]NetworkLogItem      `json:"network,omitempty"`
	Number         int                    `json:"number"`
	Screenshot     *Asset                 `json:"screenshot"`
	Selector       *string                `json:"selector"`
	SessionReplay  *Asset                 `json:"session_replay"`
	Url            *string                `json:"url"`
	VideoRecording *Asset                 `json:"video_recording"`
	VoiceNote      *Asset                 `json:"voice_note"`
}

// PinLite defines model for PinLite.
type PinLite struct {
	Attachments []Attachment           `json:"attachments"`
	ElementInfo map[string]interface{} `json:"element_info"`
	Feedback    string                 `json:"feedback"`
	Metadata    map[string]interface{} `json:"metadata"`
	Number      int                    `json:"number"`
	Selector    *string                `json:"selector"`
	Url         *string                `json:"url"`
}

// Project defines model for Project.
type Project struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// Reporter defines model for Reporter.
type Reporter struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
}

// SearchPinsResponse defines model for SearchPinsResponse.
type SearchPinsResponse struct {
	Results []struct {
		Pin     PinLite        `json:"pin"`
		Session SessionSummary `json:"session"`
	} `json:"results"`
	Total int `json:"total"`
}

// SearchSessionsResponse defines model for SearchSessionsResponse.
type SearchSessionsResponse struct {
	Results []SessionSummary `json:"results"`
	Total   int              `json:"total"`
}

// SessionAttachment defines model for SessionAttachment.
type SessionAttachment struct {
	ContentType string `json:"content_type"`
	Filename    string `json:"filename"`
	Id          int    `json:"id"`
	PinNumber   int    `json:"pin_number"`
	SizeBytes   int    `json:"size_bytes"`
}

// SessionDetail defines model for SessionDetail.
type SessionDetail struct {
	Pins                 []PinLite           `json:"pins"`
	Project              *Project            `json:"project"`
	ProjectSessionNumber int                 `json:"project_session_number"`
	ReportUrl            string              `json:"report_url"`
	Reporter             *Reporter           `json:"reporter"`
	Status               SessionDetailStatus `json:"status"`
	TeamSlug             string              `json:"team_slug"`
	Title                string              `json:"title"`
	UpdatedAt            time.Time           `json:"updated_at"`
	Url                  string              `json:"url"`
}

// SessionDetailStatus defines model for SessionDetail.Status.
type SessionDetailStatus string

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	Attachments          []SessionAttachment  `json:"attachments"`
	FirstPinFeedback     string               `json:"first_pin_feedback"`
	FreeTierLocked       bool                 `json:"free_tier_locked"`
	PinCount             int                  `json:"pin_count"`
	Project              *Project             `json:"project"`
	ProjectSessionNumber int                  `json:"project_session_number"`
	ReportUrl            string               `json:"report_url"`
	Reporter             *Reporter            `json:"reporter"`
	Status               SessionSummaryStatus `json:"status"`
	TeamSlug             string               `json:"team_slug"`
	Title                string               `json:"title"`
	UpdatedAt            time.Time            `json:"updated_at"`
	Url                  string               `json:"url"`
}

// SessionSummaryStatus defines model for SessionSummary.Status.
type SessionSummaryStatus string

// UserEventItem defines model for UserEventItem.
type UserEventItem struct {
	Target               *interface{}           `json:"target,omitempty"`
	Timestamp            *interface{}           `json:"timestamp,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AttachmentID defines model for AttachmentID.
type AttachmentID = int

// PinNumber defines model for PinNumber.
type PinNumber = int

// ProjectID defines model for ProjectID.
type ProjectID = int

// SessionNumber defines model for SessionNumber.
type SessionNumber = int

// TeamSlug defines model for TeamSlug.
type TeamSlug = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// SearchParams defines parameters for Search.
type SearchParams struct {
	// Q Search query text.
	Q string `form:"q" json:"q"`

	// Scope Search scope.
	Scope *SearchParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// Limit Maximum number of results to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchParamsScope defines parameters for Search.
type SearchParamsScope string

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// Status Filter sessions by lifecycle status.
	Status *ListSessionsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Project Filter sessions by project identifier or slug.
	Project *string `form:"project,omitempty" json:"project,omitempty"`

	// Limit Maximum number of sessions to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor from a previous list response.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListSessionsParamsStatus defines parameters for ListSessions.
type ListSessionsParamsStatus string

// GetPinByNumberParams defines parameters for GetPinByNumber.
type GetPinByNumberParams struct {
	// Fields Optional expanded fields to include.
	Fields *GetPinByNumberParamsFields `form:"fields,omitempty" json:"fields,omitempty"`
}

// GetPinByNumberParamsFields defines parameters for GetPinByNumber.
type GetPinByNumberParamsFields string

// Getter for additional properties for ConsoleLogItem. Returns the specified
// element and whether it was found
func (a ConsoleLogItem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ConsoleLogItem
func (a *ConsoleLogItem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ConsoleLogItem to handle AdditionalProperties
func (a *ConsoleLogItem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["datetime"]; found {
		err = json.Unmarshal(raw, &a.Datetime)
		if err != nil {
			return fmt.Errorf("error reading 'datetime': %w", err)
		}
		delete(object, "datetime")
	}

	if raw, found := object["epochTime"]; found {
		err = json.Unmarshal(raw, &a.EpochTime)
		if err != nil {
			return fmt.Errorf("error reading 'epochTime': %w", err)
		}
		delete(object, "epochTime")
	}

	if raw, found := object["extra"]; found {
		err = json.Unmarshal(raw, &a.Extra)
		if err != nil {
			return fmt.Errorf("error reading 'extra': %w", err)
		}
		delete(object, "extra")
	}

	if raw, found := object["full_url"]; found {
		err = json.Unmarshal(raw, &a.FullUrl)
		if err != nil {
			return fmt.Errorf("error reading 'full_url': %w", err)
		}
		delete(object, "full_url")
	}

	if raw, found := object["short_url"]; found {
		err = json.Unmarshal(raw, &a.ShortUrl)
		if err != nil {
			return fmt.Errorf("error reading 'short_url': %w", err)
		}
		delete(object, "short_url")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ConsoleLogItem to handle AdditionalProperties
func (a ConsoleLogItem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Datetime != nil {
		object["datetime"], err = json.Marshal(a.Datetime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'datetime': %w", err)
		}
	}

	if a.EpochTime != nil {
		object["epochTime"], err = json.Marshal(a.EpochTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'epochTime': %w", err)
		}
	}

	if a.Extra != nil {
		object["extra"], err = json.Marshal(a.Extra)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'extra': %w", err)
		}
	}

	if a.FullUrl != nil {
		object["full_url"], err = json.Marshal(a.FullUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'full_url': %w", err)
		}
	}

	if a.ShortUrl != nil {
		object["short_url"], err = json.Marshal(a.ShortUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'short_url': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	if a.Value != nil {
		object["value"], err = json.Marshal(a.Value)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'value': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for NetworkLogItem. Returns the specified
// element and whether it was found
func (a NetworkLogItem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NetworkLogItem
func (a *NetworkLogItem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NetworkLogItem to handle AdditionalProperties
func (a *NetworkLogItem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["body"]; found {
		err = json.Unmarshal(raw, &a.Body)
		if err != nil {
			return fmt.Errorf("error reading 'body': %w", err)
		}
		delete(object, "body")
	}

	if raw, found := object["epochTime"]; found {
		err = json.Unmarshal(raw, &a.EpochTime)
		if err != nil {
			return fmt.Errorf("error reading 'epochTime': %w", err)
		}
		delete(object, "epochTime")
	}

	if raw, found := object["full_url"]; found {
		err = json.Unmarshal(raw, &a.FullUrl)
		if err != nil {
			return fmt.Errorf("error reading 'full_url': %w", err)
		}
		delete(object, "full_url")
	}

	if raw, found := object["headers"]; found {
		err = json.Unmarshal(raw, &a.Headers)
		if err != nil {
			return fmt.Errorf("error reading 'headers': %w", err)
		}
		delete(object, "headers")
	}

	if raw, found := object["method"]; found {
		err = json.Unmarshal(raw, &a.Method)
		if err != nil {
			return fmt.Errorf("error reading 'method': %w", err)
		}
		delete(object, "method")
	}

	if raw, found := object["short_url"]; found {
		err = json.Unmarshal(raw, &a.ShortUrl)
		if err != nil {
			return fmt.Errorf("error reading 'short_url': %w", err)
		}
		delete(object, "short_url")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NetworkLogItem to handle AdditionalProperties
func (a NetworkLogItem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Body != nil {
		object["body"], err = json.Marshal(a.Body)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'body': %w", err)
		}
	}

	if a.EpochTime != nil {
		object["epochTime"], err = json.Marshal(a.EpochTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'epochTime': %w", err)
		}
	}

	if a.FullUrl != nil {
		object["full_url"], err = json.Marshal(a.FullUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'full_url': %w", err)
		}
	}

	if a.Headers != nil {
		object["headers"], err = json.Marshal(a.Headers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'headers': %w", err)
		}
	}

	if a.Method != nil {
		object["method"], err = json.Marshal(a.Method)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'method': %w", err)
		}
	}

	if a.ShortUrl != nil {
		object["short_url"], err = json.Marshal(a.ShortUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'short_url': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for UserEventItem. Returns the specified
// element and whether it was found
func (a UserEventItem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for UserEventItem
func (a *UserEventItem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for UserEventItem to handle AdditionalProperties
func (a *UserEventItem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["target"]; found {
		err = json.Unmarshal(raw, &a.Target)
		if err != nil {
			return fmt.Errorf("error reading 'target': %w", err)
		}
		delete(object, "target")
	}

	if raw, found := object["timestamp"]; found {
		err = json.Unmarshal(raw, &a.Timestamp)
		if err != nil {
			return fmt.Errorf("error reading 'timestamp': %w", err)
		}
		delete(object, "timestamp")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for UserEventItem to handle AdditionalProperties
func (a UserEventItem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Target != nil {
		object["target"], err = json.Marshal(a.Target)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'target': %w", err)
		}
	}

	if a.Timestamp != nil {
		object["timestamp"], err = json.Marshal(a.Timestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timestamp': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RevokeToken request
	RevokeToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMe request
	GetMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Search request
	Search(ctx context.Context, params *SearchParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSessions request
	ListSessions(ctx context.Context, params *ListSessionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSession request
	GetSession(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPinByNumber request
	GetPinByNumber(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, params *GetPinByNumberParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadAttachment request
	DownloadAttachment(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, attachmentId AttachmentID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RevokeToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeTokenRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Search(ctx context.Context, params *SearchParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSessions(ctx context.Context, params *ListSessionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSessionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSession(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSessionRequest(c.Server, teamSlug, projectId, sessionNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPinByNumber(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, params *GetPinByNumberParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPinByNumberRequest(c.Server, teamSlug, projectId, sessionNumber, pinNumber, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadAttachment(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, attachmentId AttachmentID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadAttachmentRequest(c.Server, teamSlug, projectId, sessionNumber, pinNumber, attachmentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRevokeTokenRequest generates requests for RevokeToken
func NewRevokeTokenRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/agent/revoke/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMeRequest generates requests for GetMe
func NewGetMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/me/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSearchRequest generates requests for Search
func NewSearchRequest(server string, params *SearchParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/search/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "q", runtime.ParamLocationQuery, params.Q); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Scope != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "scope", runtime.ParamLocationQuery, *params.Scope); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.Limit != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSessionsRequest generates requests for ListSessions
func NewListSessionsRequest(server string, params *ListSessionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/sessions/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Status != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.Project != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project", runtime.ParamLocationQuery, *params.Project); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.Limit != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.Cursor != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSessionRequest generates requests for GetSession
func NewGetSessionRequest(server string, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "team_slug", runtime.ParamLocationPath, teamSlug)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "project_id", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "session_number", runtime.ParamLocationPath, sessionNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/teams/%s/projects/%s/sessions/%s/", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPinByNumberRequest generates requests for GetPinByNumber
func NewGetPinByNumberRequest(server string, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, params *GetPinByNumberParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "team_slug", runtime.ParamLocationPath, teamSlug)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "project_id", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "session_number", runtime.ParamLocationPath, sessionNumber)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "pin_number", runtime.ParamLocationPath, pinNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/teams/%s/projects/%s/sessions/%s/pins/by-number/%s/", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Fields != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "fields", runtime.ParamLocationQuery, *params.Fields); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDownloadAttachmentRequest generates requests for DownloadAttachment
func NewDownloadAttachmentRequest(server string, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, attachmentId AttachmentID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "team_slug", runtime.ParamLocationPath, teamSlug)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "project_id", runtime.ParamLocationPath, projectId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "session_number", runtime.ParamLocationPath, sessionNumber)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "pin_number", runtime.ParamLocationPath, pinNumber)
	if err != nil {
		return nil, err
	}

	var pathParam4 string

	pathParam4, err = runtime.StyleParamWithLocation("simple", false, "attachment_id", runtime.ParamLocationPath, attachmentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/teams/%s/projects/%s/sessions/%s/pins/by-number/%s/attachments/%s/download/", pathParam0, pathParam1, pathParam2, pathParam3, pathParam4)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RevokeTokenWithResponse request
	RevokeTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RevokeTokenResp, error)

	// GetMeWithResponse request
	GetMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeResp, error)

	// SearchWithResponse request
	SearchWithResponse(ctx context.Context, params *SearchParams, reqEditors ...RequestEditorFn) (*SearchResp, error)

	// ListSessionsWithResponse request
	ListSessionsWithResponse(ctx context.Context, params *ListSessionsParams, reqEditors ...RequestEditorFn) (*ListSessionsResp, error)

	// GetSessionWithResponse request
	GetSessionWithResponse(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, reqEditors ...RequestEditorFn) (*GetSessionResp, error)

	// GetPinByNumberWithResponse request
	GetPinByNumberWithResponse(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, params *GetPinByNumberParams, reqEditors ...RequestEditorFn) (*GetPinByNumberResp, error)

	// DownloadAttachmentWithResponse request
	DownloadAttachmentWithResponse(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, attachmentId AttachmentID, reqEditors ...RequestEditorFn) (*DownloadAttachmentResp, error)
}

type RevokeTokenResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r RevokeTokenResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeTokenResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMeResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Me
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r GetMeResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMeResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
	JSON400 *BadRequest
	JSON401 *Unauthorized
}

// Status returns HTTPResponse.Status
func (r SearchResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSessionsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListSessionsResponse
	JSON401      *Unauthorized
}

// Status returns HTTPResponse.Status
func (r ListSessionsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSessionsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSessionResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SessionDetail
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetSessionResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSessionResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPinByNumberResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PinFull
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetPinByNumberResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPinByNumberResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadAttachmentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r DownloadAttachmentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadAttachmentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RevokeTokenWithResponse request returning *RevokeTokenResp
func (c *ClientWithResponses) RevokeTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RevokeTokenResp, error) {
	rsp, err := c.RevokeToken(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeTokenResp(rsp)
}

// GetMeWithResponse request returning *GetMeResp
func (c *ClientWithResponses) GetMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeResp, error) {
	rsp, err := c.GetMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMeResp(rsp)
}

// SearchWithResponse request returning *SearchResp
func (c *ClientWithResponses) SearchWithResponse(ctx context.Context, params *SearchParams, reqEditors ...RequestEditorFn) (*SearchResp, error) {
	rsp, err := c.Search(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchResp(rsp)
}

// ListSessionsWithResponse request returning *ListSessionsResp
func (c *ClientWithResponses) ListSessionsWithResponse(ctx context.Context, params *ListSessionsParams, reqEditors ...RequestEditorFn) (*ListSessionsResp, error) {
	rsp, err := c.ListSessions(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSessionsResp(rsp)
}

// GetSessionWithResponse request returning *GetSessionResp
func (c *ClientWithResponses) GetSessionWithResponse(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, reqEditors ...RequestEditorFn) (*GetSessionResp, error) {
	rsp, err := c.GetSession(ctx, teamSlug, projectId, sessionNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSessionResp(rsp)
}

// GetPinByNumberWithResponse request returning *GetPinByNumberResp
func (c *ClientWithResponses) GetPinByNumberWithResponse(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, params *GetPinByNumberParams, reqEditors ...RequestEditorFn) (*GetPinByNumberResp, error) {
	rsp, err := c.GetPinByNumber(ctx, teamSlug, projectId, sessionNumber, pinNumber, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPinByNumberResp(rsp)
}

// DownloadAttachmentWithResponse request returning *DownloadAttachmentResp
func (c *ClientWithResponses) DownloadAttachmentWithResponse(ctx context.Context, teamSlug TeamSlug, projectId ProjectID, sessionNumber SessionNumber, pinNumber PinNumber, attachmentId AttachmentID, reqEditors ...RequestEditorFn) (*DownloadAttachmentResp, error) {
	rsp, err := c.DownloadAttachment(ctx, teamSlug, projectId, sessionNumber, pinNumber, attachmentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadAttachmentResp(rsp)
}

// ParseRevokeTokenResp parses an HTTP response from a RevokeTokenWithResponse call
func ParseRevokeTokenResp(rsp *http.Response) (*RevokeTokenResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeTokenResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest
	}

	return response, nil
}

// ParseGetMeResp parses an HTTP response from a GetMeWithResponse call
func ParseGetMeResp(rsp *http.Response) (*GetMeResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMeResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Me
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseSearchResp parses an HTTP response from a SearchWithResponse call
func ParseSearchResp(rsp *http.Response) (*SearchResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseListSessionsResp parses an HTTP response from a ListSessionsWithResponse call
func ParseListSessionsResp(rsp *http.Response) (*ListSessionsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSessionsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListSessionsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetSessionResp parses an HTTP response from a GetSessionWithResponse call
func ParseGetSessionResp(rsp *http.Response) (*GetSessionResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSessionResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SessionDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetPinByNumberResp parses an HTTP response from a GetPinByNumberWithResponse call
func ParseGetPinByNumberResp(rsp *http.Response) (*GetPinByNumberResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPinByNumberResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PinFull
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDownloadAttachmentResp parses an HTTP response from a DownloadAttachmentWithResponse call
func ParseDownloadAttachmentResp(rsp *http.Response) (*DownloadAttachmentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadAttachmentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
